/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentationIndexRouteImport } from './routes/documentation.index'
import { Route as DocumentationUserGuideRouteImport } from './routes/documentation.user-guide'
import { Route as DocumentationTechnicalRouteImport } from './routes/documentation.technical'
import { Route as DocumentationChangelogRouteImport } from './routes/documentation.changelog'

const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationIndexRoute = DocumentationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentationRoute,
} as any)
const DocumentationUserGuideRoute = DocumentationUserGuideRouteImport.update({
  id: '/user-guide',
  path: '/user-guide',
  getParentRoute: () => DocumentationRoute,
} as any)
const DocumentationTechnicalRoute = DocumentationTechnicalRouteImport.update({
  id: '/technical',
  path: '/technical',
  getParentRoute: () => DocumentationRoute,
} as any)
const DocumentationChangelogRoute = DocumentationChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => DocumentationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRouteWithChildren
  '/documentation/changelog': typeof DocumentationChangelogRoute
  '/documentation/technical': typeof DocumentationTechnicalRoute
  '/documentation/user-guide': typeof DocumentationUserGuideRoute
  '/documentation/': typeof DocumentationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documentation/changelog': typeof DocumentationChangelogRoute
  '/documentation/technical': typeof DocumentationTechnicalRoute
  '/documentation/user-guide': typeof DocumentationUserGuideRoute
  '/documentation': typeof DocumentationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRouteWithChildren
  '/documentation/changelog': typeof DocumentationChangelogRoute
  '/documentation/technical': typeof DocumentationTechnicalRoute
  '/documentation/user-guide': typeof DocumentationUserGuideRoute
  '/documentation/': typeof DocumentationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documentation'
    | '/documentation/changelog'
    | '/documentation/technical'
    | '/documentation/user-guide'
    | '/documentation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documentation/changelog'
    | '/documentation/technical'
    | '/documentation/user-guide'
    | '/documentation'
  id:
    | '__root__'
    | '/'
    | '/documentation'
    | '/documentation/changelog'
    | '/documentation/technical'
    | '/documentation/user-guide'
    | '/documentation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentationRoute: typeof DocumentationRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation/': {
      id: '/documentation/'
      path: '/'
      fullPath: '/documentation/'
      preLoaderRoute: typeof DocumentationIndexRouteImport
      parentRoute: typeof DocumentationRoute
    }
    '/documentation/user-guide': {
      id: '/documentation/user-guide'
      path: '/user-guide'
      fullPath: '/documentation/user-guide'
      preLoaderRoute: typeof DocumentationUserGuideRouteImport
      parentRoute: typeof DocumentationRoute
    }
    '/documentation/technical': {
      id: '/documentation/technical'
      path: '/technical'
      fullPath: '/documentation/technical'
      preLoaderRoute: typeof DocumentationTechnicalRouteImport
      parentRoute: typeof DocumentationRoute
    }
    '/documentation/changelog': {
      id: '/documentation/changelog'
      path: '/changelog'
      fullPath: '/documentation/changelog'
      preLoaderRoute: typeof DocumentationChangelogRouteImport
      parentRoute: typeof DocumentationRoute
    }
  }
}

interface DocumentationRouteChildren {
  DocumentationChangelogRoute: typeof DocumentationChangelogRoute
  DocumentationTechnicalRoute: typeof DocumentationTechnicalRoute
  DocumentationUserGuideRoute: typeof DocumentationUserGuideRoute
  DocumentationIndexRoute: typeof DocumentationIndexRoute
}

const DocumentationRouteChildren: DocumentationRouteChildren = {
  DocumentationChangelogRoute: DocumentationChangelogRoute,
  DocumentationTechnicalRoute: DocumentationTechnicalRoute,
  DocumentationUserGuideRoute: DocumentationUserGuideRoute,
  DocumentationIndexRoute: DocumentationIndexRoute,
}

const DocumentationRouteWithChildren = DocumentationRoute._addFileChildren(
  DocumentationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentationRoute: DocumentationRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
